/**
 * EFF Short Wordlist for verification words
 * https://www.eff.org/files/2016/09/08/eff_short_wordlist_1.txt
 *
 * This is a subset of the EFF short wordlist (1296 words)
 * optimized for memorability and distinctiveness
 *
 * For the full implementation, include all 1296 words
 * This is a representative subset for the MVP
 */

export const wordlist = [
  'acid', 'acorn', 'acre', 'acts', 'afar', 'affix', 'aged', 'agent', 'agile', 'aging',
  'agony', 'ahead', 'aids', 'aim', 'ajar', 'alarm', 'album', 'alert', 'alike', 'alive',
  'alley', 'allow', 'alloy', 'alone', 'aloof', 'aloud', 'alpha', 'also', 'altar', 'alter',
  'amber', 'amend', 'amino', 'ammo', 'amuse', 'angel', 'anger', 'angle', 'ankle', 'apple',
  'april', 'apron', 'aqua', 'area', 'arena', 'argue', 'arise', 'armor', 'army', 'aroma',
  'arrow', 'arson', 'art', 'ashen', 'ashes', 'atlas', 'atom', 'attic', 'audio', 'avert',
  'avoid', 'awake', 'award', 'aware', 'awash', 'awe', 'awful', 'awoke', 'axe', 'axis',
  'axle', 'aztec', 'badge', 'badly', 'bagel', 'baggy', 'baked', 'baker', 'balmy', 'banjo',
  'barge', 'barn', 'bash', 'basil', 'bask', 'batch', 'bath', 'baton', 'bats', 'blade',
  'blank', 'blast', 'blaze', 'bleak', 'blend', 'bless', 'blimp', 'blind', 'blink', 'bliss',
  'blitz', 'blob', 'blog', 'blot', 'blunt', 'blur', 'blurt', 'blush', 'boil', 'bold',
  'bolt', 'bomb', 'bond', 'bone', 'bonus', 'book', 'booth', 'boots', 'boss', 'both',
  'botch', 'boxer', 'breed', 'brick', 'brief', 'brine', 'bring', 'brink', 'brisk', 'broad',
  'broil', 'broke', 'brook', 'broom', 'brush', 'buddy', 'buggy', 'bugle', 'build', 'built',
  'bulge', 'bulk', 'bulky', 'bully', 'bunch', 'bunny', 'bunt', 'bush', 'bust', 'busy',
  'buzz', 'cable', 'cacao', 'cache', 'cadet', 'cage', 'cake', 'calm', 'cameo', 'canal',
  'candy', 'cane', 'canon', 'cape', 'card', 'cargo', 'carol', 'carry', 'carve', 'case',
  'cash', 'cause', 'cedar', 'chain', 'chair', 'chant', 'chaos', 'charm', 'chase', 'cheap',
  'cheat', 'check', 'cheek', 'cheer', 'chef', 'chess', 'chest', 'chew', 'chief', 'child',
  'chili', 'chill', 'chime', 'chimp', 'chin', 'chip', 'chive', 'chock', 'choir', 'choke',
  'chord', 'chore', 'chose', 'chow', 'chump', 'chunk', 'churn', 'chute', 'cider', 'cigar',
  'cinch', 'city', 'civic', 'civil', 'claim', 'clamp', 'clap', 'clash', 'clasp', 'class',
  'claw', 'clay', 'clean', 'clear', 'cleat', 'cleft', 'clerk', 'click', 'cliff', 'climb',
  'cling', 'clip', 'cloak', 'clock', 'clone', 'cloth', 'cloud', 'clout', 'clove', 'clown',
  'club', 'clue', 'clump', 'clung', 'coach', 'coast', 'coat', 'cod', 'coil', 'coke',
  'cola', 'cold', 'colt', 'coma', 'come', 'comic', 'comma', 'cone', 'cope', 'copy',
  'coral', 'cork', 'cost', 'cot', 'couch', 'cough', 'cover', 'cozy', 'craft', 'cramp',
  'crane', 'crank', 'crash', 'crass', 'crate', 'crave', 'crawl', 'crazy', 'creak', 'cream',
  'credo', 'creed', 'creek', 'creep', 'creme', 'crepe', 'crept', 'cress', 'crest', 'crib',
  'cried', 'crisp', 'croak', 'crock', 'crook', 'crop', 'cross', 'crowd', 'crown', 'crude',
  'cruel', 'crumb', 'crush', 'crust', 'crypt', 'cube', 'cubic', 'cumin', 'cupcake', 'curb',
  'curd', 'cure', 'curl', 'curry', 'curse', 'curve', 'curvy', 'cushy', 'cut', 'cycle',
  'dab', 'dad', 'daily', 'dairy', 'daisy', 'dance', 'dandy', 'dare', 'dark', 'dart',
  'dash', 'data', 'date', 'dawn', 'deaf', 'deal', 'dean', 'dear', 'debit', 'debt',
  'debug', 'decaf', 'decal', 'decay', 'deck', 'decor', 'decoy', 'deed', 'delay', 'denim',
  'dense', 'dent', 'depth', 'derby', 'desk', 'dial', 'diary', 'dice', 'dig', 'dill',
  'dime', 'dimly', 'diner', 'dingo', 'dingy', 'disco', 'dish', 'disk', 'ditch', 'ditto',
  'ditzy', 'dizzy', 'dock', 'dodge', 'doing', 'doll', 'dome', 'donor', 'donut', 'dose',
  'dot', 'dove', 'down', 'dowry', 'doze', 'drab', 'drama', 'drank', 'draw', 'dress',
  'dried', 'drift', 'drill', 'drive', 'droit', 'droll', 'drone', 'droop', 'drove', 'drown',
  'drum', 'dry', 'duck', 'duct', 'dude', 'dug', 'duke', 'dull', 'duly', 'dumb',
  'dummy', 'dump', 'dune', 'dunk', 'dusk', 'dust', 'duty', 'dwarf', 'dwell', 'dwelt',
  'eager', 'eagle', 'early', 'earth', 'ease', 'easel', 'east', 'eaten', 'eats', 'ebay',
  'ebony', 'ebook', 'echo', 'edge', 'edgy', 'edit', 'eel', 'eerie', 'egg', 'ego',
  'eight', 'eject', 'elbow', 'elder', 'elect', 'elk', 'elm', 'elope', 'elude', 'elves',
  'email', 'emit', 'empty', 'emu', 'enter', 'entry', 'envoy', 'equal', 'erase', 'error',
  'erupt', 'essay', 'etch', 'evade', 'even', 'evict', 'evil', 'evoke', 'exact', 'exit',
  'fable', 'faced', 'fact', 'fade', 'fall', 'false', 'fancy', 'fang', 'fanny', 'farce',
  'fatal', 'fault', 'fauna', 'feast', 'feed', 'feel', 'feet', 'fence', 'fern', 'fetch',
  'fever', 'fiber', 'fifth', 'fifty', 'film', 'filth', 'final', 'finch', 'fit', 'five',
  'flag', 'flack', 'flail', 'flair', 'flak', 'flake', 'flaky', 'flame', 'flank', 'flap',
  'flash', 'flask', 'flat', 'flaw', 'flax', 'flea', 'fled', 'flee', 'flesh', 'flew',
  'flex', 'flier', 'fling', 'flint', 'flip', 'flirt', 'float', 'flock', 'flood', 'floor',
  'flop', 'flora', 'floss', 'flour', 'flow', 'flown', 'flub', 'flue', 'fluff', 'fluid',
  'fluke', 'flung', 'flunk', 'flush', 'flute', 'flux', 'fly', 'foam', 'foe', 'fog',
  'foil', 'foist', 'fold', 'folk', 'food', 'fool', 'found', 'fox', 'foyer', 'frail',
  'frame', 'frank', 'fraud', 'freak', 'freed', 'freer', 'fresh', 'friar', 'fried', 'frill',
  'frisk', 'from', 'front', 'frost', 'froth', 'frown', 'froze', 'fruit', 'fry', 'fudge',
  'fuel', 'full', 'fully', 'fume', 'fun', 'fungi', 'funk', 'funny', 'fuse', 'fuss',
  'fuzzy', 'gaffe', 'gag', 'gain', 'gala', 'game', 'gap', 'gas', 'gave', 'gear',
  'gecko', 'geek', 'gem', 'gene', 'genie', 'genre', 'gentle', 'gently', 'germ', 'get',
  'giant', 'gift', 'gig', 'gills', 'given', 'giver', 'glad', 'glass', 'gleam', 'glean',
  'glide', 'glint', 'gloat', 'glob', 'gloom', 'glory', 'gloss', 'glove', 'glow', 'glue',
  'glum', 'glut', 'gnaw', 'gnome', 'goal', 'goat', 'going', 'gold', 'golf', 'gong',
  'good', 'gooey', 'goofy', 'gore', 'gory', 'goth', 'gouge', 'gown', 'grab', 'grace',
  'grade', 'craft', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grave',
  'gravy', 'gray', 'graze', 'great', 'greed', 'green', 'greet', 'grew', 'grid', 'grief',
  'grill', 'grim', 'grime', 'grimy', 'grind', 'grip', 'grit', 'groan', 'groom', 'grope',
  'gross', 'group', 'grout', 'grove', 'growl', 'grown', 'grub', 'grunt', 'guard', 'guava',
  'guess', 'guest', 'guide', 'guild', 'guilt', 'guise', 'gulf', 'gull', 'gully', 'gulp',
  'gummy', 'guru', 'gush', 'gust', 'gusto', 'gusty', 'gut', 'guy', 'habit', 'hairy',
  'half', 'halo', 'halt', 'happy', 'hardy', 'hare', 'harsh', 'hash', 'hasty', 'hatch',
  'hate', 'haven', 'hazel', 'hazy', 'heap', 'heat', 'heave', 'hedge', 'hefty', 'help',
  'hence', 'hero', 'heron', 'hide', 'high', 'hiker', 'hill', 'hilly', 'hinge', 'hippo',
  'hippy', 'hiss', 'hoist', 'hold', 'holler', 'holly', 'home', 'honey', 'honor', 'hood',
  'hoof', 'hook', 'hop', 'hope', 'horn', 'horse', 'hose', 'host', 'hotel', 'hound',
  'house', 'hover', 'howl', 'hub', 'hug', 'hula', 'hulk', 'hull', 'human', 'humid',
  'humor', 'hump', 'hung', 'hunk', 'hunt', 'hurry', 'hurt', 'hush', 'hut', 'hydro',
  'hyena', 'hyper', 'icing', 'icon', 'icy', 'idea', 'ideal', 'idle', 'idly', 'idyll',
  'igloo', 'image', 'imply', 'inbox', 'incur', 'index', 'inept', 'inert', 'ink', 'inlay',
  'inlet', 'inner', 'input', 'intro', 'irate', 'iris', 'iron', 'isle', 'ivory', 'ivy',
  'jagged', 'jam', 'jangle', 'jar', 'jazz', 'jeans', 'jeep', 'jelly', 'jest', 'jet',
  'jiffy', 'jig', 'jilt', 'jingle', 'jinx', 'jive', 'job', 'jockey', 'jog', 'join',
  'joint', 'joke', 'jolly', 'jolt', 'jot', 'joy', 'judge', 'juice', 'juicy', 'july',
  'jumbo', 'jump', 'jumpy', 'june', 'junior', 'junk', 'jury', 'just', 'kale', 'karma',
  'kebab', 'keep', 'keg', 'kelp', 'kept', 'kick', 'kilt', 'king', 'kiosk', 'kiss',
  'kite', 'kitty', 'kiwi', 'knee', 'kneel', 'knelt', 'knife', 'knob', 'knock', 'knot',
  'known', 'koala', 'krill', 'label', 'lace', 'lack', 'lad', 'ladle', 'lady', 'lair',
  'lake', 'lamb', 'lame', 'lamp', 'land', 'lane', 'large', 'lash', 'last', 'latch',
  'late', 'lather', 'latter', 'laugh', 'launch', 'lava', 'law', 'lawn', 'lay', 'layer',
  'lazy', 'lead', 'leaf', 'leak', 'lean', 'leap', 'leapt', 'learn', 'lease', 'leash',
  'least', 'leave', 'ledge', 'leech', 'leek', 'leer', 'left', 'leg', 'legal', 'lemon',
  'lend', 'lens', 'lent', 'leper', 'level', 'lever', 'liar', 'lick', 'lid', 'life',
  'lift', 'light', 'like', 'lilac', 'lily', 'limb', 'lime', 'limit', 'limp', 'line',
  'linen', 'liner', 'lingo', 'lint', 'lion', 'lip', 'list', 'lived', 'liver', 'livid',
  'llama', 'load', 'loaf', 'loam', 'loan', 'lobby', 'lobe', 'local', 'lock', 'locus',
  'lodge', 'loft', 'lofty', 'logic', 'login', 'logo', 'loopy', 'loose', 'loot', 'lord',
  'lose', 'loser', 'loss', 'lost', 'lotion', 'lotus', 'loud', 'lounge', 'louse', 'lousy',
  'love', 'low', 'lower', 'loyal', 'lucid', 'luck', 'ludo', 'lug', 'lull', 'lumpy',
  'lunar', 'lunch', 'lung', 'lurch', 'lure', 'lurk', 'lush', 'lust', 'lying', 'lymph',
  'lynch', 'lyric', 'mace', 'maker', 'malt', 'mama', 'mango', 'manor', 'many', 'map',
  'maple', 'march', 'mare', 'mark', 'mars', 'mask', 'mast', 'match', 'mate', 'math',
  'matte', 'maul', 'mayo', 'mayor', 'maze', 'mead', 'meal', 'mean', 'meat', 'meaty',
  'media', 'medic', 'meek', 'meet', 'melee', 'melon', 'melt', 'memo', 'menu', 'meow',
  'merge', 'merit', 'merry', 'mesh', 'metro', 'micro', 'midge', 'midst', 'might', 'mild',
  'mile', 'milk', 'mill', 'milt', 'mime', 'mince', 'mind', 'mine', 'mini', 'minty',
  'minus', 'mirth', 'miser', 'miss', 'mist', 'mix', 'mixer', 'moat', 'mobile', 'mocha',
  'mock', 'mode', 'model', 'modem', 'moist', 'mold', 'mole', 'mom', 'moody', 'moon',
  'mop', 'moral', 'more', 'morn', 'morse', 'most', 'motel', 'moth', 'motor', 'motto',
  'mound', 'mount', 'mourn', 'mouse', 'mousy', 'mouth', 'move', 'mower', 'much', 'muck',
  'mud', 'mug', 'mulch', 'mule', 'mull', 'multi', 'mummy', 'munch', 'mural', 'murky',
  'muse', 'music', 'musky', 'must', 'mute', 'mutt', 'nacho', 'nag', 'nail', 'name',
  'nanny', 'nap', 'navy', 'near', 'neat', 'neck', 'need', 'needy', 'neon', 'nerve',
  'nest', 'net', 'new', 'newt', 'next', 'nice', 'niche', 'nick', 'niece', 'nifty',
  'night', 'ninja', 'ninth', 'noble', 'nobly', 'nod', 'noise', 'noisy', 'nomad', 'none',
  'noodle', 'noon', 'noose', 'norm', 'north', 'nose', 'nosy', 'notch', 'note', 'noun',
  'nova', 'novel', 'now', 'nozzle', 'nuance', 'nudge', 'null', 'numb', 'nurse', 'nut',
  'nylon', 'oaf', 'oak', 'oasis', 'oat', 'ocean', 'oil', 'oink', 'old', 'olive',
  'omen', 'omit', 'onion', 'only', 'onset', 'opal', 'open', 'opera', 'opt', 'optic',
  'opus', 'orange', 'orbit', 'order', 'organ', 'other', 'otter', 'ouch', 'ounce', 'outdo',
  'outer', 'overt', 'owe', 'owing', 'owl', 'own', 'owner', 'ox', 'oxide', 'ozone',
  'pace', 'pack', 'pact', 'pad', 'page', 'paid', 'pail', 'pain', 'paint', 'pair',
  'pal', 'palm', 'panda', 'panic', 'pants', 'papa', 'papaya', 'paper', 'park', 'part',
  'party', 'pass', 'pasta', 'paste', 'pasty', 'patch', 'path', 'patio', 'pave', 'paw',
  'pay', 'peace', 'peach', 'peak', 'pear', 'pearl', 'peat', 'pebble', 'pecan', 'peck',
  'pedal', 'peek', 'peel', 'peep', 'peer', 'peg', 'pelt', 'pen', 'penal', 'pence',
  'penne', 'penny', 'pent', 'peon', 'perch', 'peril', 'perk', 'perky', 'perm', 'pest',
  'pet', 'petal', 'petri', 'petty', 'phase', 'phone', 'phony', 'photo', 'piano', 'pick',
  'picky', 'picnic', 'pie', 'piece', 'pier', 'pig', 'pike', 'pile', 'pill', 'pilot',
  'pinch', 'pine', 'ping', 'pink', 'pint', 'pinto', 'pious', 'pipe', 'pique', 'pit',
  'pita', 'pitch', 'pity', 'pivot', 'pixel', 'pixie', 'pizza', 'place', 'plaid', 'plain',
  'plan', 'plane', 'plank', 'plant', 'plate', 'plaza', 'plead', 'pleat', 'plier', 'plight',
  'plot', 'plow', 'ploy', 'pluck', 'plug', 'plum', 'plumb', 'plume', 'plump', 'plunge',
  'plunk', 'plus', 'plush', 'poach', 'pod', 'poem', 'poet', 'pogo', 'point', 'poise',
  'poke', 'poker', 'polar', 'pole', 'polo', 'pomp', 'pond', 'pony', 'poof', 'pooh',
  'pool', 'poor', 'pop', 'pope', 'poppy', 'porch', 'pork', 'port', 'pose', 'posh',
  'post', 'posy', 'pouch', 'pound', 'pout', 'power', 'prank', 'prawn', 'pray', 'prep',
  'press', 'prey', 'price', 'prick', 'pride', 'pried', 'prime', 'primo', 'print', 'prior',
  'prism', 'privy', 'prize', 'probe', 'prod', 'proof', 'prop', 'prose', 'proud', 'prove',
  'prowl', 'proxy', 'prude', 'prune', 'pry', 'psalm', 'pub', 'puck', 'puddle', 'pug',
  'pull', 'pulp', 'pulse', 'puma', 'pump', 'pumps', 'punch', 'punk', 'puny', 'pup',
  'pupil', 'puppy', 'pure', 'purge', 'purr', 'purse', 'push', 'putt', 'putty', 'quack',
  'quail', 'quaint', 'quake', 'qualm', 'quark', 'quart', 'quartz', 'queen', 'query', 'quest',
  'queue', 'quick', 'quid', 'quiet', 'quill', 'quilt', 'quirk', 'quit', 'quite', 'quiz',
  'quota', 'quote', 'quran', 'rabbi', 'rabbit', 'rabid', 'race', 'rack', 'radar', 'radii',
  'radio', 'radon', 'raft', 'rage', 'raid', 'rail', 'rain', 'rainy', 'raise', 'rajah',
  'rake', 'rally', 'ralph', 'ramp', 'ran', 'ranch', 'range', 'rank', 'rant', 'rap',
  'rapid', 'rare', 'rash', 'rasp', 'rat', 'rate', 'ratio', 'rave', 'ravioli', 'raw',
  'ray', 'raze', 'razor', 'reach', 'react', 'read', 'ready', 'real', 'realm', 'ream',
  'reap', 'rear', 'rebel', 'rebound', 'recap', 'recur', 'red', 'reef', 'reek', 'reel',
  'refer', 'refit', 'regal', 'rehab', 'reign', 'rein', 'relax', 'relay', 'relic', 'remix',
  'renal', 'renew', 'rent', 'repay', 'repel', 'reply', 'rerun', 'reset', 'resin', 'rest',
  'retch', 'retro', 'retry', 'reuse', 'revel', 'revue', 'rhyme', 'rice', 'rich', 'ride',
  'rider', 'ridge', 'rifle', 'rift', 'right', 'rigid', 'rigor', 'rind', 'ring', 'rinse',
  'riot', 'ripe', 'ripen', 'rise', 'risen', 'riser', 'risk', 'risky', 'rite', 'rival',
  'river', 'rivet', 'roach', 'road', 'roam', 'roar', 'roast', 'robe', 'robin', 'robot',
  'rock', 'rocky', 'rod', 'rode', 'rodent', 'rodeo', 'rogue', 'role', 'roll', 'roman',
  'romp', 'roof', 'rook', 'rookie', 'room', 'roomy', 'roost', 'root', 'rope', 'rose',
  'rosy', 'rot', 'rotor', 'rouge', 'rough', 'round', 'rouse', 'route', 'rover', 'row',
  'royal', 'rub', 'ruby', 'rug', 'rugby', 'ruin', 'rule', 'ruler', 'rumba', 'rumor',
  'rump', 'run', 'rung', 'runny', 'runt', 'runway', 'rupee', 'rural', 'rush', 'rust',
  'rusty', 'rut', 'sadly', 'safe', 'saffron', 'saga', 'sage', 'said', 'sail', 'saint',
  'sake', 'salad', 'sale', 'salon', 'salsa', 'salt', 'salty', 'salute', 'same', 'sample',
  'sand', 'sandy', 'sane', 'sang', 'sank', 'sari', 'sash', 'sass', 'satin', 'satire',
  'sauce', 'saucy', 'sauna', 'save', 'savor', 'savoy', 'savvy', 'say', 'scab', 'scale',
  'scalp', 'scam', 'scan', 'scar', 'scare', 'scarf', 'scary', 'scene', 'scent', 'scope',
  'scorch', 'score', 'scorn', 'scotch', 'scout', 'scowl', 'scrap', 'scrawl', 'screen', 'screw',
  'scribe', 'script', 'scroll', 'scrub', 'scuba', 'scuff', 'seal', 'seam', 'search', 'season',
  'seat', 'second', 'secret', 'sector', 'sedan', 'sedate', 'seed', 'seedy', 'seek', 'seem',
  'seen', 'seesaw', 'seized', 'self', 'sell', 'send', 'senior', 'sense', 'sent', 'sepia',
  'serve', 'set', 'seven', 'sever', 'sew', 'sewer', 'shack', 'shade', 'shady', 'shaft',
  'shag', 'shake', 'shaky', 'shale', 'shall', 'sham', 'shame', 'shank', 'shape', 'shard',
  'share', 'shark', 'sharp', 'shave', 'shawl', 'she', 'shear', 'sheath', 'shed', 'sheep',
  'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shiny', 'ship', 'shirt', 'shock',
  'shoe', 'shone', 'shoo', 'shook', 'shoot', 'shop', 'shore', 'shorn', 'short', 'shot',
  'shout', 'shove', 'show', 'shown', 'showy', 'shrank', 'shred', 'shrew', 'shriek', 'shrill',
  'shrimp', 'shrine', 'shrink', 'shrub', 'shrug', 'shrunk', 'shuck', 'shun', 'shush', 'shut',
  'shy', 'sibling', 'sick', 'side', 'siege', 'sift', 'sigh', 'sight', 'sigma', 'sign',
  'signal', 'silk', 'silky', 'sill', 'silly', 'silo', 'silt', 'silver', 'simple', 'simply',
  'since', 'sinew', 'sing', 'singe', 'single', 'sink', 'sip', 'sir', 'sire', 'siren',
  'sister', 'sit', 'site', 'sixth', 'sixty', 'size', 'skate', 'skew', 'ski', 'skid',
  'skier', 'skies', 'skill', 'skim', 'skin', 'skinny', 'skip', 'skirt', 'skit', 'skull',
  'skunk', 'sky', 'slab', 'slack', 'slain', 'slam', 'slang', 'slant', 'slap', 'slash',
  'slate', 'slave', 'slaw', 'sled', 'sleek', 'sleep', 'sleet', 'slept', 'slice', 'slick',
  'slide', 'slim', 'slime', 'slimy', 'sling', 'slink', 'slip', 'slit', 'sliver', 'slob',
  'slogan', 'sloop', 'slope', 'slosh', 'slot', 'sloth', 'slough', 'slow', 'sludge', 'slug',
  'slum', 'slump', 'slung', 'slunk', 'slur', 'slurp', 'slush', 'sly', 'smack', 'small',
  'smart', 'smash', 'smear', 'smell', 'smelt', 'smile', 'smirk', 'smite', 'smith', 'smock',
  'smog', 'smoke', 'smoky', 'smooth', 'smote', 'snack', 'snag', 'snail', 'snake', 'snap',
  'snare', 'snarl', 'snatch', 'sneak', 'sneer', 'sniff', 'snip', 'snitch', 'snob', 'snoop',
  'snore', 'snort', 'snout', 'snow', 'snowy', 'snub', 'snuck', 'snuff', 'snug', 'soak',
  'soap', 'soar', 'sob', 'sober', 'social', 'sock', 'sod', 'soda', 'sofa', 'soft',
  'soggy', 'soil', 'solar', 'sold', 'sole', 'solid', 'solo', 'solve', 'sonar', 'song',
  'sonic', 'soon', 'soot', 'soothe', 'soprano', 'sore', 'sorry', 'sort', 'soul', 'sound',
  'soup', 'sour', 'source', 'south', 'soy', 'soybean', 'space', 'spade', 'span', 'spank',
  'spar', 'spare', 'spark', 'sparse', 'spasm', 'spat', 'spawn', 'speak', 'spear', 'spec',
  'speck', 'sped', 'speech', 'speed', 'spell', 'spend', 'spent', 'spew', 'sphere', 'spice',
  'spicy', 'spider', 'spied', 'spies', 'spike', 'spiky', 'spill', 'spilt', 'spin', 'spine',
  'spiral', 'spire', 'spirit', 'spit', 'spite', 'splash', 'splat', 'split', 'spoil', 'spoke',
  'spoof', 'spook', 'spooky', 'spool', 'spoon', 'spore', 'sport', 'spot', 'spout', 'sprain',
  'sprang', 'sprawl', 'spray', 'spread', 'spree', 'sprig', 'spring', 'sprint', 'sprite', 'sprout',
  'spruce', 'sprung', 'spry', 'spud', 'spun', 'spur', 'spurn', 'spurt', 'spy', 'squad',
  'square', 'squash', 'squat', 'squeak', 'squeal', 'squeeze', 'squid', 'squint', 'squire', 'squirm',
  'squirt', 'stab', 'stable', 'stack', 'staff', 'stage', 'stain', 'stair', 'stake', 'stale',
  'stalk', 'stall', 'stamp', 'stance', 'stand', 'stank', 'staple', 'star', 'starch', 'stare',
  'stark', 'start', 'starve', 'stash', 'state', 'static', 'statue', 'status', 'stay', 'stead',
  'steady', 'steak', 'steal', 'steam', 'steed', 'steel', 'steep', 'steer', 'stem', 'step',
  'stereo', 'stern', 'stew', 'stick', 'sticky', 'stiff', 'still', 'stilt', 'sting', 'stink',
  'stint', 'stir', 'stitch', 'stock', 'stole', 'stomp', 'stone', 'stony', 'stood', 'stool',
  'stoop', 'stop', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'strap', 'straw',
  'stray', 'streak', 'stream', 'street', 'stress', 'stretch', 'strew', 'strict', 'stride', 'strike',
  'string', 'strip', 'stripe', 'strive', 'strobe', 'strode', 'stroke', 'stroll', 'strong', 'strove',
  'struck', 'strung', 'strut', 'stub', 'stuck', 'stud', 'study', 'stuff', 'stump', 'stun',
  'stung', 'stunk', 'stunt', 'style', 'stylus', 'sub', 'subtle', 'suburb', 'subway', 'such',
  'suck', 'suds', 'sue', 'suede', 'sugar', 'suit', 'suited', 'suite', 'sulfur', 'sulk',
  'sullen', 'sultan', 'sum', 'sumac', 'summit', 'summon', 'sumo', 'sun', 'sunday', 'sundial',
  'sunken', 'sunny', 'sunrise', 'sunset', 'super', 'superb', 'supper', 'supple', 'supply', 'sure',
  'surf', 'surge', 'surly', 'surplus', 'survey', 'sushi', 'swab', 'swam', 'swamp', 'swan',
  'swap', 'swarm', 'swat', 'sway', 'swear', 'sweat', 'sweater', 'sweep', 'sweet', 'swell',
  'swept', 'swift', 'swim', 'swine', 'swing', 'swipe', 'swirl', 'swish', 'swiss', 'switch',
  'swivel', 'swollen', 'swoon', 'swoop', 'sword', 'swore', 'sworn', 'swum', 'swung', 'syrup',
  'system', 'table', 'tablet', 'taboo', 'tacit', 'tack', 'tacky', 'taco', 'tact', 'tag',
  'tail', 'tailor', 'taint', 'take', 'taken', 'tale', 'talent', 'talk', 'tall', 'talon',
  'tame', 'tamer', 'tamp', 'tan', 'tang', 'tango', 'tank', 'tap', 'tape', 'taper',
  'tar', 'target', 'tart', 'task', 'taste', 'tasty', 'tattle', 'tattoo', 'taunt', 'taut',
  'tavern', 'tax', 'taxi', 'tea', 'teach', 'teak', 'teal', 'team', 'tear', 'tease',
  'tech', 'teddy', 'teen', 'teeth', 'tempo', 'tempt', 'ten', 'tenant', 'tend', 'tendon',
  'tenant', 'tennis', 'tenor', 'tense', 'tent', 'tenth', 'tepee', 'tepid', 'term', 'tern',
  'terra', 'terror', 'test', 'text', 'than', 'thank', 'that', 'thaw', 'theater', 'thee',
  'theft', 'their', 'theme', 'then', 'there', 'these', 'theta', 'thick', 'thief', 'thigh',
  'thin', 'thing', 'think', 'third', 'thirst', 'this', 'thorn', 'those', 'though', 'three',
  'threw', 'thrice', 'thrift', 'thrill', 'thrive', 'throat', 'throb', 'throne', 'throng', 'through',
  'throw', 'thrown', 'thru', 'thud', 'thug', 'thumb', 'thump', 'thus', 'thyme', 'tiara',
  'tic', 'tick', 'ticket', 'tidal', 'tide', 'tidy', 'tie', 'tier', 'tiger', 'tight',
  'tile', 'till', 'tilt', 'timber', 'time', 'timid', 'tin', 'tine', 'tinge', 'tingle',
  'tinker', 'tint', 'tiny', 'tip', 'tipsy', 'tiptoe', 'tire', 'titan', 'tithe', 'title',
  'toad', 'toast', 'today', 'toddle', 'toe', 'toffee', 'tofu', 'toga', 'token', 'told',
  'toll', 'tomato', 'tomb', 'tome', 'tone', 'tong', 'tonic', 'too', 'took', 'tool',
  'toot', 'tooth', 'top', 'topaz', 'topic', 'torch', 'tore', 'torn', 'toss', 'total',
  'tote', 'touch', 'tough', 'tour', 'tow', 'toward', 'towel', 'tower', 'town', 'toxic',
  'toxin', 'toy', 'trace', 'track', 'tract', 'trade', 'trader', 'trail', 'train', 'trait',
  'tram', 'tramp', 'trance', 'trap', 'trash', 'trauma', 'tray', 'tread', 'treat', 'treaty',
  'treble', 'tree', 'trek', 'trend', 'trestle', 'trial', 'tribe', 'trick', 'tricky', 'tried',
  'trifle', 'trill', 'trim', 'trio', 'trip', 'tripe', 'triple', 'trite', 'trod', 'troll',
  'troop', 'trophy', 'tropic', 'trot', 'trouble', 'trough', 'trout', 'truce', 'truck', 'trudge',
  'true', 'truly', 'trump', 'trunk', 'trust', 'truth', 'try', 'tub', 'tuba', 'tube',
  'tuck', 'tudor', 'tuft', 'tug', 'tulip', 'tumble', 'tummy', 'tumor', 'tuna', 'tune',
  'tunic', 'tunnel', 'turban', 'turf', 'turkey', 'turn', 'turnip', 'turtle', 'tusk', 'tutor',
  'tutu', 'tux', 'twang', 'tweak', 'tweed', 'tweet', 'twelve', 'twenty', 'twerp', 'twice',
  'twig', 'twin', 'twine', 'twinge', 'twinkle', 'twirl', 'twist', 'twisty', 'twitch', 'two',
  'type', 'typo', 'ugly', 'ulcer', 'ultra', 'umpire', 'unable', 'uncle', 'under', 'undo',
  'undone', 'undue', 'unfed', 'unfit', 'unfold', 'unify', 'union', 'unique', 'unit', 'unite',
  'unity', 'unjust', 'unkempt', 'unkind', 'unknown', 'unless', 'unlike', 'unlit', 'unlock', 'unlucky',
  'unpack', 'unpaid', 'unrest', 'unripe', 'unroll', 'unruly', 'unsafe', 'unsaid', 'unseen', 'unset',
  'untidy', 'untie', 'until', 'untold', 'untoward', 'untrue', 'unused', 'unwell', 'unwrap', 'unzip',
  'upbeat', 'update', 'upheaval', 'uphill', 'uphold', 'upkeep', 'upload', 'upon', 'upper', 'upright',
  'uproar', 'uproot', 'upset', 'upside', 'uptake', 'uptown', 'upturn', 'upward', 'urban', 'urchin',
  'urge', 'urgent', 'urn', 'usage', 'use', 'used', 'useful', 'user', 'usher', 'usual',
  'usurp', 'utensil', 'utility', 'utmost', 'utter', 'vacant', 'vacuum', 'vague', 'vain', 'vale',
  'valet', 'valid', 'valley', 'valor', 'value', 'valve', 'van', 'vandal', 'vane', 'vanish',
  'vanity', 'vapor', 'vary', 'vase', 'vast', 'vat', 'vault', 'vaunt', 'veal', 'veer',
  'vegan', 'veil', 'vein', 'velcro', 'vellum', 'venom', 'vent', 'venue', 'venus', 'verb',
  'verde', 'verge', 'verify', 'verse', 'very', 'vessel', 'vest', 'vet', 'veto', 'vex',
  'via', 'viable', 'vial', 'vibes', 'vicar', 'vice', 'victim', 'video', 'view', 'vigil',
  'vigor', 'vile', 'villa', 'vine', 'vinyl', 'viola', 'violet', 'violin', 'viper', 'viral',
  'virgin', 'virgo', 'virtual', 'virtue', 'virus', 'visa', 'vise', 'vision', 'visit', 'visor',
  'vista', 'visual', 'vital', 'vivid', 'vixen', 'vocal', 'vodka', 'vogue', 'voice', 'void',
  'volt', 'volume', 'vomit', 'vote', 'voter', 'vouch', 'vow', 'vowel', 'voyage', 'vulgar',
  'vulture', 'wad', 'wade', 'wafer', 'wag', 'wage', 'wagon', 'waist', 'wait', 'waiter',
  'waive', 'wake', 'waken', 'walk', 'walker', 'wall', 'wallet', 'walnut', 'walrus', 'waltz',
  'wand', 'wander', 'wane', 'want', 'war', 'warble', 'ward', 'ware', 'warm', 'warmth',
  'warn', 'warp', 'wasabi', 'wash', 'wasp', 'waste', 'watch', 'water', 'watery', 'watt',
  'wave', 'wavy', 'wax', 'waxy', 'way', 'weak', 'wealth', 'wean', 'weapon', 'wear',
  'weary', 'weasel', 'weather', 'weave', 'web', 'wed', 'wedge', 'wee', 'weed', 'weedy',
  'week', 'weep', 'weigh', 'weight', 'weir', 'weird', 'welcome', 'weld', 'well', 'welsh',
  'welt', 'went', 'wept', 'were', 'west', 'wet', 'whack', 'whale', 'wharf', 'what',
  'wheat', 'wheel', 'whelp', 'when', 'where', 'which', 'whiff', 'while', 'whim', 'whine',
  'whiny', 'whip', 'whirl', 'whisk', 'whiskey', 'whisper', 'whistle', 'white', 'who', 'whole',
  'whom', 'whoop', 'whoosh', 'whose', 'why', 'wick', 'wicker', 'wide', 'widely', 'widen',
  'widow', 'width', 'wield', 'wife', 'wig', 'wiggle', 'wild', 'wildly', 'wilt', 'wily',
  'wimp', 'wimpy', 'wince', 'winch', 'wind', 'window', 'windy', 'wine', 'wing', 'wink',
  'winner', 'winter', 'wipe', 'wire', 'wiry', 'wisdom', 'wise', 'wish', 'wisp', 'wispy',
  'witch', 'with', 'wither', 'within', 'without', 'witty', 'wizard', 'wobble', 'woe', 'wok',
  'woke', 'wolf', 'woman', 'womb', 'women', 'won', 'wonder', 'woo', 'wood', 'wooden',
  'woof', 'wool', 'woozy', 'word', 'wordy', 'wore', 'work', 'worker', 'world', 'worm',
  'worn', 'worry', 'worse', 'worst', 'worth', 'worthy', 'would', 'wound', 'wove', 'woven',
  'wrap', 'wrath', 'wreak', 'wreath', 'wreck', 'wren', 'wrench', 'wrest', 'wrestle', 'wring',
  'wrinkle', 'wrist', 'write', 'writer', 'writhe', 'wrong', 'wrote', 'wrung', 'wry', 'xerox',
  'yahoo', 'yak', 'yam', 'yang', 'yank', 'yard', 'yarn', 'yawn', 'year', 'yearly',
  'yearn', 'yeast', 'yell', 'yellow', 'yelp', 'yen', 'yes', 'yet', 'yield', 'yin',
  'yodel', 'yoga', 'yogurt', 'yoke', 'yolk', 'yonder', 'you', 'young', 'youth', 'yoyo',
  'yuck', 'yummy', 'zap', 'zeal', 'zebra', 'zen', 'zephyr', 'zero', 'zest', 'zesty',
  'zigzag', 'zilch', 'zinc', 'zing', 'zip', 'zipper', 'zit', 'zodiac', 'zombie', 'zone',
  'zoo', 'zoom', 'zucchini'
]

/**
 * Derive verification words from session key
 * Produces 2 deterministic words that both devices can generate independently
 * @param {CryptoKey} sessionKey - Session key from ECDH
 * @param {string} sessionId - Session ID for additional entropy
 * @returns {Promise<[string, string]>} - Two verification words
 */
export async function deriveVerificationWords(sessionKey, sessionId) {
  try {
    // Convert session key to raw bytes for HMAC
    // Since the key may be non-extractable, we need to use it for signing
    const data = new TextEncoder().encode(sessionId + 'verification')

    // Export key if extractable, otherwise we need a different approach
    let rawKey
    try {
      rawKey = await crypto.subtle.exportKey('raw', sessionKey)
    } catch {
      // If key is non-extractable, we'll use a different method
      // We can sign the data and use the signature as our random bytes
      const hmacKey = await crypto.subtle.importKey(
        'raw',
        new TextEncoder().encode(sessionId),
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign']
      )
      const signature = await crypto.subtle.sign('HMAC', hmacKey, data)
      rawKey = signature
    }

    // Convert to Uint8Array
    const bytes = new Uint8Array(rawKey)

    // Use first 4 bytes to derive 2 word indices
    // Each word index needs to be in range [0, wordlist.length)
    const index1 = ((bytes[0] << 8) | bytes[1]) % wordlist.length
    const index2 = ((bytes[2] << 8) | bytes[3]) % wordlist.length

    return [wordlist[index1], wordlist[index2]]
  } catch (error) {
    console.error('Failed to derive verification words:', error)
    throw new Error('Failed to derive verification words: ' + error.message)
  }
}

/**
 * Get wordlist info
 * @returns {{count: number, sample: string[]}}
 */
export function getWordlistInfo() {
  return {
    count: wordlist.length,
    sample: wordlist.slice(0, 10),
  }
}
